name: Deploy CD

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to DockerHub
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build . --file Dockerfile --tag epgarzonr/appHello:latest
        docker push epgarzonr/appHello:latest

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          sudo apt update -y
          sudo apt install -y docker
          sudo service docker start
          sudo usermod -a -G docker ec2-user

          sudo docker pull epgarzonr/appHello:latest

          sudo docker ps -q --filter "name=appHello" | grep -q . && docker stop appHello && docker rm appHello || true
          sudo docker run -d --name appHello -p 80:80 epgarzonr/appHello:latest